language: android
android:
  components:
    - tools
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_script: cd source/java/2d

script: gradle clean desktop:build android:build core:test

