before_install:
    - bash .android_license.sh
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script: cd source/java/2d

script: gradle clean desktop:build android:build core:test

