env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_ad9f1e893abb_key -iv $encrypted_ad9f1e893abb_iv
  -in deploy_android_release.tar.enc -out deploy_android_release.tar -d
- ls -l
- tar xf deploy_android_release.tar
- chmod 400 deploy.rsa
- eval `ssh-agent -s`
- cat deploy.rsa | ssh-add -
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- touch $HOME/.android/repositories.cfg
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script: cd source/java/2d
script:
- keytool -genkey -v -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
- "./gradlew clean"
- "./gradlew desktop:build"
- "./gradlew android:build"
- "./gradlew core:test jacocoTestReport"
- "./gradlew assembleRelease"
after_success:
- bash ${TRAVIS_BUILD_DIR}/.set_tags.sh
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
    secure: "ucJiyV4gA6A4Cr0rMdNnBuTEStAxVmA2krMe4sBxnPq8L02Fi+Bg/OVScWEOyyljOImRmDoF8cx6nsjQ2D5pz2opmMR9ci+n51lu3FWVdm6Cb0XFW3plxXLuvsURCoAHhKPjfgk2eLLq6/FU4Q0qyu2USfsHJizwDsFBFlZJpq6XByHH0BZZDdJosVjl1V6KOQCCYTiznOdydXdHtPc/8yf1JncMyFVgLxhD+53A4t/ulVsBMJvV/5V3jVeQyX4PFwPKCKHeYnEppnmFyypTWUS3fqH2qti3tlkR3cXqXa1IPAHR3EFKAoBeHrBrGJ3oVe1iREiQ60ioJ0Tr8IKBB65qqKhrDY1NaIHe+hm78RMDXsucVX/WOVL5/OpZ2AtlDRHxqkLIYHUhr9OvIy5aon2MvYsHTZ3LnRKTg0KjlfgeMhXTf0ttYftFDgottJjvbTcPvbrGENOzB6VjrgeAVZVW6sJNZBLMzNziyfgdOiY5efwc4w/XqOaBwSVbdvdbtEO89P8yJe/F5BgSs3MtNslYtq15RGjXV496oH5OMZWx0XnKaiX3xSKq/8aOHtxsCRjBlYfj+7fevV7JxKTIPrMzThko+CXauiTP1554YKI8lYITccTpWyfPmkMPk49XPpzLYtrLJrUFaBFLT5mljlHsd9tMiF13f6xa/u+oxb4="
  file: "${TRAVIS_BUILD_DIR}/source/java/2d/android/build/outputs/apk/*/android-*.apk"   
  file_glob: true
  on:
    repo: memellis/SlotPuzzle
    tags: true
    branch: master 
