env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_ad9f1e893abb_key -iv $encrypted_ad9f1e893abb_iv
  -in deploy_android_release.tar.enc -out deploy_android_release.tar -d
- ls -l
- tar xf deploy_android_release.tar
- chmod 400 deploy.rsa
- eval `ssh-agent -s`
- cat deploy.rsa | ssh-add -
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- touch $HOME/.android/repositories.cfg
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script: cd source/java/2d
script:
- keytool -genkey -v -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
- "./gradlew clean"
- "./gradlew desktop:build"
- "./gradlew android:build"
- "./gradlew core:test jacocoTestReport"
- "./gradlew assembleRelease"
after_success:
- bash ${TRAVIS_BUILD_DIR}/.set_tags.sh
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
  secure: "GA9qnI/l16sTXaE2oagR0mPt/Xv2O1EFZcdcyQmPbPly8y424ZFgHCH9KlVccv3wlKa4nUdAp7d/63EfOi2ZtrRW8Yez2iO9R4gHormhixVsmEQfB9rrb3Udaf4mEpTUcz7VrdQxteta3rJ98rVY2oD/JPSD+zjjNAMiqhJgwuMOiotOm2LRR03sQYsV9pS8QOidJvYOyF8mGI65LaPkbHb3ismffiRiOw9ftZY6CYY8dqWF/2BOHeNJ4UquXzi7O8wZKa07aJhhIZappmSvyhRdVbRHiNV0j096zzDaB721H3c2o9ZCjaqkb1EBJcDL8uikpa8cneOc2ERq5fItIF05QZRJCkKBqCoqE05TFCa8tH3Uah7q686lU0DOZmpIro86/Umf6o1ClvoKr7AIFtnSxfnykqzxKPulkPVpt/QlppPsEaqWTBR4zGth8k0Lxc3BxT4mfXGHwopT9Gih5blIY1L03+VaTccZoxZztavOXMcAOwbr98+qLZ5Pl+E35+vpTJKAz4rtS2D4eT3K4+m8JS16F4GuEJqlHLiZ4a2KRX08UnMZHub9AllOOJTmwUNMlF75wZyIcdNfOqqLaxR3FG0En9aFwD67CssIXXrlqgNofEnTbhvIIdtxKjXrKvr2Tx+nINT6UiBU8r13OsXZBg0db2AdmVWPQ6cSHkY="
  file: "${TRAVIS_BUILD_DIR}/source/java/2d/android/build/outputs/apk/*/android-*.apk"   
  file_glob: true
  on:
    repo: memellis/SlotPuzzle
    tags: true
    branch: master 
