before_install:
    - openssl aes-256-cbc -K $encrypted_10d1b62feeba_key -iv $encrypted_10d1b62feeba_iv -in .deploy.rsa.enc -out .deploy.rsa -d
    - bash .android_license.sh
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script: cd source/java/2d

script: gradle clean desktop:build android:build core:test

after_success:
    - eval "$(ssh-agent)"
    - chmod 600 ./deploy.rsa
    - ssh-add ./deploy.rsa
    - bash .set_tags.sh

deploy: 
    provider: releases 
    api_key: "GITHUB OAUTH TOKEN" 
    file: "source/java/2d/android/build/outputs/apk/android-debug.apk" 
    skip_cleanup: true 
    on: 
        tags: true 
