before_install:
    - openssl aes-256-cbc -K $encrypted_fda7b6caa8fd_key -iv $encrypted_fda7b6caa8fd_iv -in .deploy.rsa.enc -out .deploy.rsa -d
    - bash .android_license.sh
language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script: cd source/java/2d

script: gradle clean desktop:build android:build core:test

after_success:
    - eval "$(ssh-agent)"
    - chmod 600 ./deploy.rsa
    - ssh-add ./deploy.rsa
    - bash .set_tags.sh

deploy: 
    provider: releases 
    api_key: "GITHUB OAUTH TOKEN" 
    file: "source/java/2d/android/build/outputs/apk/android-debug.apk" 
    skip_cleanup: true 
    on: 
        tags: true 


Sponsored by:
 _____ _
|_ _| ___ ___ ___ _| | _ _ ___ ___
  | |  | -_|| _|| . || . || | || || -_|
  |_| |___||_| |__,||___||_ ||_|_||___|
                           |___|
root@localhost:/# sp 
root@localhost:/usr/local/src/SlotPuzzle# ssh-keygen 
-C "memellis@gmail.com" -t rsa -b 4096 Generating 
public/private rsa key pair. Enter file in which to 
save the key (/root/.ssh/id_rsa): .deploy.rsa Enter 
passphrase (empty for no passphrase): Enter same 
passphrase again: Your identification has been saved 
in .deploy.rsa. Your public key has been saved in 
.deploy.rsa.pub. The key fingerprint is: 
91:0c:d1:56:b9:c9:0d:03:04:f2:40:15:fe:51:98:e9 
memellis@gmail.com The key's randomart image is: 
+---[RSA 4096]----+
|   .+.**o*o.  |
|     = o*o+ |
|      oo=. * |
|       .Eo+ .  |
|        S |
|                 |
|                 |
|                 |
|                 |
+-----------------+ 
root@localhost:/usr/local/src/SlotPuzzle# travis 
encrypt-file .deploy.rsa encrypting .deploy.rsa for 
memellis/SlotPuzzle storing result as 
.deploy.rsa.enc storing secure env variables for 
decryption Please add the following to your build 
script (before_install stage in your .travis.yml, 
for instance):
     Pro Tip: You can add it automatically 
by running with --add. Make sure to add 
.deploy.rsa.enc to the git repository. Make sure not 
to add .deploy.rsa to the git repository. Commit all 
changes to your .travis.yml.
root@localhost:/usr/local/src/SlotPuzzle# travis encrypt-file .deploy.rsaa
