MyGame
MyGame/gdx-game
MyGame/gdx-game/.classpath
MyGame/gdx-game/.project
MyGame/gdx-game/libs
MyGame/gdx-game/libs/gdx.jar
MyGame/gdx-game/src
MyGame/gdx-game/src/com
MyGame/gdx-game/src/com/mycompany
MyGame/gdx-game/src/com/mycompany/mygame
MyGame/gdx-game/src/com/mycompany/mygame/MyGdxGame.java
MyGame/gdx-game-android
MyGame/gdx-game-android/.classpath
MyGame/gdx-game-android/.project
MyGame/gdx-game-android/AndroidManifest.xml
MyGame/gdx-game-android/assets
MyGame/gdx-game-android/assets/android.jpg
MyGame/gdx-game-android/bin
MyGame/gdx-game-android/bin/jardex
MyGame/gdx-game-android/bin/jardex/gdx.jar.dex
MyGame/gdx-game-android/bin/jardex/gdx-backend-android.jar.dex
MyGame/gdx-game-android/libs
MyGame/gdx-game-android/libs/armeabi
MyGame/gdx-game-android/libs/armeabi/libgdx.so
MyGame/gdx-game-android/libs/armeabi/libgdx-box2d.so
MyGame/gdx-game-android/libs/armeabi-v7a
MyGame/gdx-game-android/libs/armeabi-v7a/libgdx.so
MyGame/gdx-game-android/libs/armeabi-v7a/libgdx-box2d.so
MyGame/gdx-game-android/libs/gdx-backend-android.jar
MyGame/gdx-game-android/libs/x86
MyGame/gdx-game-android/libs/x86/libgdx.so
MyGame/gdx-game-android/libs/x86/libgdx-box2d.so
MyGame/gdx-game-android/project.properties
MyGame/gdx-game-android/res
MyGame/gdx-game-android/res/drawable-hdpi
MyGame/gdx-game-android/res/drawable-hdpi/ic_launcher.png
MyGame/gdx-game-android/res/drawable-ldpi
MyGame/gdx-game-android/res/drawable-ldpi/ic_launcher.png
MyGame/gdx-game-android/res/drawable-mdpi
MyGame/gdx-game-android/res/drawable-mdpi/ic_launcher.png
MyGame/gdx-game-android/res/layout
MyGame/gdx-game-android/res/layout/main.xml
MyGame/gdx-game-android/res/values
MyGame/gdx-game-android/res/values/strings.xml
MyGame/gdx-game-android/src
MyGame/gdx-game-android/src/com
MyGame/gdx-game-android/src/com/mycompany
MyGame/gdx-game-android/src/com/mycompany/mygame
MyGame/gdx-game-android/src/com/mycompany/mygame/MainActivity.java
MyGame/gdx-game-android/gen
MyGame/gdx-game-android/gen/com
MyGame/gdx-game-android/gen/com/mycompany
MyGame/gdx-game-android/gen/com/mycompany/mygame
MyGame/gdx-game-android/gen/com/mycompany/mygame/R.java
MyGame/gdx-game-android/gen/com/mycompany/mygame/BuildConfig.java
