name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 8.0.362+8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build SampleApplication
      run: cd source/java/2d && ./gradlew --no-daemon build